[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Variables de entorno - IMPORTANTE: Configurar estas en el dashboard de Railway
# No uses este archivo para credenciales sensibles en producción
[env]
# Credenciales SMTP - CONFIGURAR EN RAILWAY DASHBOARD
SMTP_EMAIL=ceidsoporte.flch@unmsm.edu.pe
SMTP_APP_PASSWORD=dgjr jxdm dske dxos
SMTP_FROM_NAME=Centro de Idiomas
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
FLASK_SECRET_KEY=change-me-in-production

# Configuración adicional
PORT=5000